/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-svg-transformer
export {};

declare global {
  export type SvgName = 'download' | 'social/twitter' | 'vite' | 'vue-2' | 'vue' | 'default'
  interface Window {
    ust: {
      options: { cacheDir?: string, global: boolean, libraryDir?: string, svgDir?: string, useTypes: boolean, isTesting: boolean, isNuxt: boolean, nuxtDir: string, fallback: string, svg: { classDefault?: string[], clearSize: 'all' | 'parent' | 'none', clearClass: 'all' | 'parent' | 'none', clearStyle: 'all' | 'parent' | 'none', currentColor: boolean, inlineStyleDefault?: string[], sizeInherit: boolean, title?: boolean }, warning: boolean }
      svgList: Record<SvgName, () => Promise<{ default: string }>>
      importSvg: (name: SvgName) => Promise<string>
    }
  }
}

declare module 'vue' {
  export interface GlobalComponents {
    SvgIcon: typeof import('./dist/vue')['SvgIcon']
  }
}

window.ust = {
  options: options || {},
  svgList: svgList || {},
  importSvg: importSvg || function () {},
} || {}
