/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-svg-transformer
export {};

declare global {
  type SvgType = 'download' | 'default'
  interface Window {
    svgList: Record<SvgType, Promise<{ default: string }>>
    importSvg: (name: SvgType) => Promise<string>
  }
}

declare module 'vue' {
  export interface GlobalComponents {
    SvgIcon: typeof import('./dist/vue')['SvgIcon']
  }
}

window.svgList = window.svgList || {}
window.importSvg = importSvg || function () {}
