/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-svg-transformer
export type SvgName = 'download' | 'social/twitter' | 'vite' | 'vue-2' | 'vue' | 'default'
export const options = {
  fallback: "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"32\" height=\"32\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 8.45v4M12 21a9 9 0 1 1 0-18a9 9 0 0 1 0 18Zm.05-5.55v.1h-.1v-.1h.1Z\"/></svg>",
  svg: {
    classDefault: [
      "svg-icon"
    ],
    clearSize: "all",
    clearClass: "all",
    clearStyle: "all",
    currentColor: true,
    inlineStyleDefault: [
      "display: inline-block; vertical-align: middle;"
    ],
    sizeInherit: true,
    title: true
  },
  warning: false,
  cacheDir: "./node_modules/unplugin-svg-transformer/cache",
  global: false,
  libraryDir: "./src",
  svgDir: "./src/svg",
  useTypes: true
}
export const svgList: Record<SvgName, () => Promise<{ default: string }>> = {
  'download': () => import('../node_modules/unplugin-svg-transformer/cache/download.ts'),
  'social/twitter': () => import('../node_modules/unplugin-svg-transformer/cache/social/twitter.ts'),
  'vite': () => import('../node_modules/unplugin-svg-transformer/cache/vite.ts'),
  'vue-2': () => import('../node_modules/unplugin-svg-transformer/cache/vue-2.ts'),
  'vue': () => import('../node_modules/unplugin-svg-transformer/cache/vue.ts'),
  'default': () => import('../node_modules/unplugin-svg-transformer/cache/default.ts'),
}

export async function importSvg(name: SvgName): Promise<string> {
  if (!svgList[name] && options.warning)
    console.warn(`Icon ${name} not found`)
  const icon = svgList[name] || svgList["default"]
  const svg = await icon()

  return svg.default
}

if (typeof window !== 'undefined') {
  window.ust = window.ust || {}
  window.ust.options = options
  window.ust.svgList = svgList
  window.ust.importSvg = importSvg
}
