/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-svg-transformer
export const iconList: Record<IconType, Promise<{ default: string }>> = {
  'download': () => import('./.nuxt/icons/download'),
  'social/twitter': () => import('./.nuxt/icons/social/twitter'),
  'vite-2': () => import('./.nuxt/icons/vite-2'),
  'vite': () => import('./.nuxt/icons/vite'),
  'default': () => import('./.nuxt/icons/default'),
}

export async function importIcon(name: IconType): Promise<{ default: string }> {
  if (!iconList[name])
    console.warn(`Icon ${name} not found`)
  name = iconList[name] || iconList["default"]
  return await name()
}