/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-svg-transformer
export const IconList: Record<IconType, Promise<{ default: string }>> = {
  'download': () => import('./node_modules/unplugin-svg-transformer/cache/download'),
  'social/twitter': () => import('./node_modules/unplugin-svg-transformer/cache/social/twitter'),
  'default': () => import('./node_modules/unplugin-svg-transformer/cache/default'),
}

export async function importIcon(name: IconType): Promise<{ default: string }> {
  name = IconList[name] || IconList["default"]
  return await name()
}

if (typeof window !== 'undefined') {
  window.iconList = IconList
  window.importIcon = importIcon
}