export type IconType = 'download' | 'feed-apple-podcast' | 'feed-deezer' | 'feed-google-podcast' | 'feed-overcast' | 'feed-podcast-addict' | 'feed-rss' | 'feed-spotify' | 'mail' | 'player-close' | 'player-forward' | 'player-pause' | 'player-play' | 'player-playback-x1-5' | 'player-playback-x2' | 'player-playback' | 'player-rewind' | 'player-volume-off' | 'player-volume' | 'social-facebook' | 'social-twitter' | 'social-youtube' | 'default'
export const IconList: Record<IconType | string, Promise<{ default: string }>> = {
  'download': import('.\\cache\\download'),
  'feed-apple-podcast': import('.\\cache\\feed\\apple-podcast'),
  'feed-deezer': import('.\\cache\\feed\\deezer'),
  'feed-google-podcast': import('.\\cache\\feed\\google-podcast'),
  'feed-overcast': import('.\\cache\\feed\\overcast'),
  'feed-podcast-addict': import('.\\cache\\feed\\podcast-addict'),
  'feed-rss': import('.\\cache\\feed\\rss'),
  'feed-spotify': import('.\\cache\\feed\\spotify'),
  'mail': import('.\\cache\\mail'),
  'player-close': import('.\\cache\\player\\close'),
  'player-forward': import('.\\cache\\player\\forward'),
  'player-pause': import('.\\cache\\player\\pause'),
  'player-play': import('.\\cache\\player\\play'),
  'player-playback-x1-5': import('.\\cache\\player\\playback-x1.5'),
  'player-playback-x2': import('.\\cache\\player\\playback-x2'),
  'player-playback': import('.\\cache\\player\\playback'),
  'player-rewind': import('.\\cache\\player\\rewind'),
  'player-volume-off': import('.\\cache\\player\\volume-off'),
  'player-volume': import('.\\cache\\player\\volume'),
  'social-facebook': import('.\\cache\\social\\facebook'),
  'social-twitter': import('.\\cache\\social\\twitter'),
  'social-youtube': import('.\\cache\\social\\youtube'),
  'default': import('.\\cache\\default'),
}
