/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-svg-transformer
export type SvgName = 'download' | 'social/twitter' | 'vite' | 'vue-2' | 'vue' | 'default'
export const svgList: Record<SvgName, () => Promise<{ default: string }>> = {
  'download': () => import('../node_modules/unplugin-svg-transformer/cache/download.ts'),
  'social/twitter': () => import('../node_modules/unplugin-svg-transformer/cache/social/twitter.ts'),
  'vite': () => import('../node_modules/unplugin-svg-transformer/cache/vite.ts'),
  'vue-2': () => import('../node_modules/unplugin-svg-transformer/cache/vue-2.ts'),
  'vue': () => import('../node_modules/unplugin-svg-transformer/cache/vue.ts'),
  'default': () => import('../node_modules/unplugin-svg-transformer/cache/default.ts'),
}

export async function importSvg(name: SvgName): Promise<string> {
  if (!svgList[name])
    console.warn(`Icon ${name} not found`)
  name = svgList[name] || svgList["default"]
  const svg = await name()
  if (svg.default)
    return svg.default
  return svg
}

if (typeof window !== 'undefined') {
  window.svgList = svgList
  window.importSvg = importSvg
}
