/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-svg-transformer
export {};

declare global {
  export type SvgName = 'download' | 'social/twitter' | 'vite-2' | 'vite' | 'default'
  interface Window {
    svgList: Record<SvgName, () => Promise<{ default: string }>>
    importSvg: (name: SvgName) => Promise<string>
  }
}

declare module 'vue' {
  export interface GlobalComponents {
    SvgIcon: typeof import('unplugin-svg-transformer/dist/vue')['SvgIcon']
  }
}
