/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-svg-transformer
export {};

declare global {
  type SvgName = 'download' | 'social/twitter' | 'default'
  interface Window {
    svgList: Record<SvgName, () => Promise<{ default: string }>>
    importSvg: (name: SvgName) => Promise<string>
  }
}

declare module 'vue' {
  export interface GlobalComponents {
    SvgIcon: typeof import('unplugin-svg-transformer/dist/vue')['VueSvg']
    importSvg: (name: SvgName) => Promise<string>
  }
}

window.svgList = window.svgList || {}
window.importSvg = importSvg || function () {}
