/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-svg-transformer
export {};

declare global {
  type IconType = 'download' | 'social/twitter' | 'default'
  interface Window {
    iconList: Record<IconType, Promise<{ default: string }>>
    importIcon: (name: IconType | string) => Promise<{ default: string }>
  }
}

declare module 'vue' {
  export interface GlobalComponents {
    SvgIcon: typeof import('unplugin-svg-transformer/components')['VueSvg']
    importIcon: (name: IconType | string) => Promise<{ default: string }>
  }
}

window.iconList = window.iconList || {}
window.importIcon = importIcon || function () {}
