/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-svg-transformer
export {}

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    SvgIcon: typeof import('unplugin-svg-transformer/components')['default']
  }
}