/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-svg-transformer
export {}

declare global {
  export type IconType = 'download' | 'social/twitter' | 'default'

  interface Window {
    iconList: Record<IconType, Promise<{ default: string }>>
  }
}

declare module 'vue' {
  export interface GlobalComponents {
    SvgIcon: typeof import('unplugin-svg-transformer/components')['VueSvg']
  }
}

window.iconList = window.iconList || {}
