/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-svg-transformer
export const iconList: Record<IconType, Promise<{ default: string }>> = {
  'svelte': () => import('../node_modules/unplugin-svg-transformer/cache/svelte'),
  'default': () => import('../node_modules/unplugin-svg-transformer/cache/default'),
}

export async function importIcon(name: IconType): Promise<{ default: string }> {
  name = iconList[name] || iconList["default"]
  return await name()
}

if (typeof window !== 'undefined') {
  window.iconList = iconList
  window.importIcon = importIcon
}