/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-svg-transformer
export type IconType = 'download-2' | 'download' | 'social/twitter' | 'default' | 'default'

export const IconList: Record<IconType | string, Promise<{ default: string }>> = {
  'download-2': import('../node_modules/unplugin-svg-transformer/cache/download-2'),
  'download': import('../node_modules/unplugin-svg-transformer/cache/download'),
  'social/twitter': import('../node_modules/unplugin-svg-transformer/cache/social/twitter'),
  'default': import('../node_modules/unplugin-svg-transformer/cache/default'),
}

if (typeof window !== 'undefined') {
  window.iconList = IconList
}
